Adding DOCTYPE parse errors
HTMLParseErrorWG/html pull request #12
Opened 2017-05-01 05:13 UTC by diervo

2017-05-02 13:32 UTC, inikulin commented
@diervo I'll check it tomorrow if you wouldn't mind. Lot's of thing to do at the moment.

2017-05-04 12:11 UTC, inikulin requested changes

2017-05-04 12:11 UTC, inikulin commented on source
> +   <dd>This is an <dfn data-x="parser-error-abrupt-closing-of-doctype">abrupt-closing-of-doctype</dfn>
It should be pars**e**-error-abrupt-closing-of-doctype. You also will need to replace `dfn` with `span` in `Before DOCTYPE public identifier state` for this error.

2017-05-04 12:11 UTC, inikulin commented on source
> +   <dd>This is a <dfn data-x="parse-error-missing-quote-around-doctype-public-identifier">missing-quote-around-doctype-public-identifier</dfn>
Sorry for the wrong suggestion, we can reuse `missing-quote-before-doctype-public-identifier` error here.

2017-05-04 12:11 UTC, inikulin commented on source
> +   <dd>This is an <span data-x="parse-error-eof-in-doctype">eof-in-doctype</span><span>parse error</span>.
Missing space before `parse error`.

2017-05-04 12:11 UTC, inikulin commented on source
> +   <dd>This is a <dfn data-x="parse-error-missing-whitespace-after-doctype-public-identifier">missing-whitespace-after-doctype-public-identifier</dfn>
Should be same as below: `missing-whitespace-between-doctype-public-and-system-identifiers`. I guess it's caused by my misleading comment again.

2017-05-04 12:11 UTC, inikulin commented on source
> +   <dd>This is an <span data-x="parse-error-eof-in-doctype">eof-in-doctype</span><span>parse error</span>.
Missing space before `parse error`.

2017-05-04 12:11 UTC, inikulin commented on source
> +   <dd>This is an <span data-x="parse-error-eof-in-doctype">eof-in-doctype</span><span>parse error</span>.
Missing space before `parse error`.

2017-05-04 12:11 UTC, inikulin commented on source
> +   <dd>This is an <span data-x="parse-error-abrupt-closing-of-doctype">abrupt-closing-of-doctype</span>.
Missing `<span>parse error</span>`

2017-05-09 07:17 UTC, diervo commented
//cc @inikulin

2017-05-09 15:22 UTC, inikulin requested changes
@diervo a couple of issue left that were not fixed:
https://github.com/HTMLParseErrorWG/html/pull/12#discussion_r114756584
https://github.com/HTMLParseErrorWG/html/pull/12#discussion_r114756846

2017-05-09 15:28 UTC, diervo commented
@inikulin Done, sorry for being sloppy

2017-05-09 16:02 UTC, inikulin commented
@diervo No worries, sorry for the forced hurry.

2017-05-09 16:17 UTC, diervo commented
@inikulin No this is great! If we could merge everything by the end of the week will be awesome. The sooner we finish the early I can do some integrations we are blocked on :)

2017-05-09 16:18 UTC, diervo commented
Once you merge this, I will take care of the other two repos, then is only one left.

2017-05-09 16:21 UTC, inikulin commented
@diervo Give me an hour, I'm in the middle of rebasing our work on top of the upstream changes.

2017-05-09 16:27 UTC, diervo commented
No rush, I have a couple of hours in the afternoon to close whatever is remaining

Sent from my iPhone

> On May 9, 2017, at 9:21 AM, Ivan Nikulin <notifications@github.com> wrote:
> 
> @diervo Give me an hour, I'm in the middle of rebasing our work on top of the upstream changes.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2017-05-09 18:01 UTC, inikulin commented
@diervo This one still not fixed: https://github.com/HTMLParseErrorWG/html/pull/12#discussion_r114756584

2017-05-09 18:02 UTC, inikulin requested changes

2017-05-09 18:02 UTC, inikulin commented on source
> +   <dd>This is an <span data-x="parse-error-eof-in-doctype">eof-in-doctype</span><span>parse error</span>.
This one still not fixed.

2017-05-09 19:21 UTC, diervo commented
@inikulin done

2017-05-09 19:50 UTC, inikulin approved these changes

2017-05-09 19:50 UTC, merged